import './js/pets-list.js';
import './js/paws-house.js';
import './js/happy-stories.js';
import './js/faq.js';
import './js/paw-btn.js';
import './js/order-modal.js';
import './js/theme-switcher.js';
import './js/team-modal.js';
import './js/burger-menu.js';